apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: q2hos-6rz-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/q2hos-6rz-dotnet-basic-gitops